### ISSUE TITLE
pass basePath  to swagger not work

### ISSUE THREAD

**Issue by Dkaiju** [rantav/flask-restful-swagger#124]
code like below：
```
api = swagger.docs(Api(app, errors=errors, catch_all_404s=True),
                                  description='XXX', basePath='github.com/api')
```

basePath parameter is not work,basePath is still http://127.0.0.1:5000/ in resource_list.json

**Comment by oblalex** [comment]
Hey @DeKaiju, could you please tell how you've resolved this issue?

**Comment by DeKaiju** [comment]
> Hey @DeKaiju, could you please tell how you've resolved this issue?

I didn't resolve this issue. I save resource_list.json to a file and modify basePath in the file. I used a 
 version swagger UI compatible with this file to show document.
