### ISSUE TITLE
Large app best practice ?

### ISSUE THREAD

**Issue by phb95** [rantav/flask-restful-swagger#22]
First off, thanks for your work !

I'm trying to follow flask's [Large-app-how-to](https://github.com/mitsuhiko/flask/wiki/Large-app-how-to) to structure an API I would like to add Swagger support to. I'm pretty new to it and I'm not very confident about the way I'm using flask-restful-swagger with blueprints.

As of now, I'm simply repeating the swagger.docs call in every module

```
my_blueprint = Blueprint('my_blueprint', __name__)
api = swagger.docs(Api(my_blueprint), ...)
```

It seems to work but is it the right way to do it ?

**Comment by jonny166** [comment]
Hi phb95, I know I am coming into this very late, but did you manage to find a way to have the APIs from all of your blueprints appear on one swagger spec.html page?

**Comment by phb95** [comment]
Hi jonny166,

Yes I did, by calling `swagger.docs` on each `Api` object.
Afterwards, I simply followed rantav advice to not repeat the `swagger.docs` call by wrapping it into a helper function.

Hope this helps.
