### ISSUE TITLE
Looking for a maintainer for this project

### ISSUE THREAD

**Issue by rantav** [rantav/flask-restful-swagger#52]
flask-restful-swagger started as a way to solve my own pain point, in a project I was working on about a year ago. It had solved this pain for me as well as for others. 
The project right now has 62 github stars, 25 forks and close to 3k downloads from pypi during the past month. 
The project had seen a good number of pull request and bug reports and I was very happy with the community uptake. 

However, in the past months I had moved to another job and although flask-restful-swagger is still very useful for the project it was initially written for, I'm no longer working on this project and I find it very hard to give flask-restful-swagger its proper attention. The community is providing excellent feedback and pull requests, but a project needs a dedicated maintainer and right now I unfortunately cannot fulfill this commitment. 

**I'm looking for someone from the community to step up**. If found appropriate, you will get commit rights, become the official maintainer and world fame to follow. In seriousness, it does not imply more that supposedly 1-2 hours per week in general, unless you're currently working on something bigger for the project. 

Roadmap includes:

- testing and automation so that the project would be more approachable for new devs (some is in place but not enough, project unit test is missing and CI).
- Implement more intuitive  request parameters https://github.com/rantav/flask-restful-swagger/issues/18
- better community support through a mailing list, IRC etc
- Whatever's on your mind that you think is useful and the community would love. That's one of the great things in being a maintainer. 

Please either comment on this issue or reach out directly to me: rantav@gmail

Thank you all!!!

**Comment by Trii** [comment]
@rantav I am currently evaluating this project to replace our Google Cloud Endpoints solution on App Engine. If we go this route, I would gladly take over the project. I currently maintain [NoseGAE](https://github.com/Trii/NoseGAE) and make extensive use of rest apis between our own projects.

**Comment by rantav** [comment]
Thanks @Trii!
Regadless, hope you'll find this project useful. We're right now at 101 stars :+1:

**Comment by Trii** [comment]
102!

**Comment by frol** [comment]
For those who are seeking for a maintained alternative - there is another project with a very similar goal - [Flask-RESTplus](https://github.com/noirbizarre/flask-restplus). Here is [a real-life RESTful API server example](https://github.com/frol/flask-restplus-server-example), though using a patched version of Flask-RESTplus.

**Comment by Trii** [comment]
Hey @frol, it may be worthwhile to integrate https://github.com/marshmallow-code/apispec into your working repo since it combines `webargs` and `marshmallow` to provide similar functionality.

**Comment by frol** [comment]
@Trii I already use `apispec` in my patched Flask-RESTplus exactly to inspect `marshmallow` models (and since `webargs` moved on to `marshmallow` fields, I killed two birds with one stone). Do you suggest something else? (I see that it is not mentioned in the README, so I will add it there now.)

**Comment by Trii** [comment]
I didn't check the code, just the README so disregard my comment.

**Comment by frol** [comment]
@Trii I have updated the README. Thank you for your feedback anyway!

**Comment by Trii** [comment]
I'm excited to try it out on Monday!

**Comment by Hiyorimi** [comment]
We are ready to support and maintain the flask-restful-swagger, since we use it at our product at merku.ru.

**Comment by rantav** [comment]
We have a new project lead and maintainer: @niall-byrne so closing this bug :smile:
