### ISSUE TITLE
Support for Swagger 2.0?

### ISSUE THREAD

**Issue by Kosta-Github** [rantav/flask-restful-swagger#70]
Are there any plans to move over to Swagger 2.0?

**Comment by rantav** [comment]
Not that I know of ;)
No objection, just that nobody done it yet...

**Comment by PabloCastellano** [comment]
I guess this is a feature we all want, but nobody has started to do it yet. @Kosta-Github do you feel like you could start it?

**Comment by Kosta-Github** [comment]
not at the moment, since I am a complete Python newbie right now
