### ISSUE TITLE
New example, please

### ISSUE THREAD

**Issue by mserralta** [rantav/flask-restful-swagger#72]
Hi there!

I am just starting with flask and swagger. I would like to use an api_key for some methods that the clients will have to send for using them. I was not able to find documentation about this and I don't get it exploring the source code. Too much new information for me: flask, swagger, swagger-ui-js... so I don't know where to start to dig from to find the solution.

Could you extend some example to need an api_key (let's say api_key=token_test) to use it=

Thanks

**Comment by rantav** [comment]
is an api_key just a string parameters in your mind?
Did you check the examples then?
https://hackpad.com/Podcast-Thunderbolt-MhK3IleMpz5

**Comment by rantav** [comment]
is an api_key just a string parameters in your mind? 
Did you check the examples then? https://github.com/rantav/flask-restful-swagger/tree/master/examples

**Comment by mserralta** [comment]
Thanks for answering.

Yes both. api_key is an string different for every client and I checked the examples. My first approach I thought was a function executes before every request, but I guess there is some already implemented way...

I guess so for this: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#security-scheme-object-

Swagger API provides a security attribute that can have a type called "apiKey". I think it may be something similar I am looking for. On the other hand, browsing swagger-ui.js and swagger.py I did not find any way to relation this "apiKey"...

You would you manage it? 

Thanks

**Comment by mserralta** [comment]
Well, I did what I did not want to.

I added a assertion before every request to check it. A new decorator to add which keys are allowed to every operations, and modified swagger-ui.js to display some icon if an operation need an api_key to execute it.

Thanks a lot! 

If someone needs it (althought I presume it is not the best solution) I will be glad to share it!
