### ISSUE TITLE
How to add authorization protection on API?

### ISSUE THREAD

**Issue by jonny166** [rantav/flask-restful-swagger#73]
Is there a mechanism to indicate to flask-restful-swagger that certain endpoints require authorization headers on the requests?  And a way to indicate what should be in that authorization header?

**Comment by rantav** [comment]
Hi @jonny166 I don't know, I never looked into that

**Comment by jonny166** [comment]
I believe this is actually supported in swagger 2.0.  However, In case anyone else has this need before this project is upgraded to swagger 2.0, I got this working by modifying index.html and by following the guidance here: https://github.com/swagger-api/swagger-ui#custom-header-parameters---for-basic-auth-etc
