### ISSUE TITLE
I need help T-T

### ISSUE THREAD

**Issue by wangshunping** [rantav/flask-restful-swagger#89]
I have try a million times and when i click spec, there is nothing to show.
![image](https://cloud.githubusercontent.com/assets/10842398/12256497/82f99240-b938-11e5-9d03-67a8e5eba69f.png)

Thus,I have print ```api.__dict__```

This is package example

```
{'blueprint': None, 'url_part_order': 'bae', 'default_mediatype': 'application/json', 'errors': {}, 'blueprint_setup': None, 'app': <Flask 'basic'>, 'prefix': '', 'serve_challenge_on_401': False, 'add_resource': <function add_resource at 0x10d8901b8>, 'urls': {}, 'catch_all_404s': False, 'representations': OrderedDict([('application/json', <function output_json at 0x10db28500>)]), 'endpoints': set(['app/staticfiles', '/todos/{todo_id}/help', 'todo', 'app/registry', 'app/resourcelister']), 'decorators': [], 'resources': []}
```

And this is mine:

```
{'blueprint': None, 'url_part_order': 'bae', 'default_mediatype': 'application/json', 'errors': {}, 'blueprint_setup': None, 'app': None, 'prefix': '', 'serve_challenge_on_401': False, 'add_resource': <function add_resource at 0x10fc3a2a8>, 'urls': {}, 'catch_all_404s': False, 'representations': OrderedDict([('application/json', <function output_json at 0x10fed2140>)]), 'endpoints': set([]), 'decorators': [], 'resources': [(<class 'flask_restful_swagger.swagger.SwaggerRegistry'>, ('/api/spec', '/api/spec.json', '/api/spec.html'), {'endpoint': 'app/registry'}), (<class 'flask_restful_swagger.swagger.ResourceLister'>, ('/api/spec/_/resource_list.json',), {'endpoint': 'app/resourcelister'}), (<class 'flask_restful_swagger.swagger.StaticFiles'>, ('/api/spec/_/static/<string:dir1>/<string:dir2>/<string:dir3>', '/api/spec/_/static/<string:dir1>/<string:dir2>', '/api/spec/_/static/<string:dir1>'), {'endpoint': 'app/staticfiles'}), (<class 'flask_restful_swagger.swagger.SwaggerResource'>, ('/user.help.json', '/user.help.html'), {'endpoint': '/user/help'}), (<class 'app.views.UserJifenView'>, ('/user',), {}), (<class 'flask_restful_swagger.swagger.SwaggerResource'>, ('/todos/{todo_id}.help.json', '/todos/{todo_id}.help.html'), {'endpoint': '/todos/{todo_id}/help'}), (<class 'app.views.Todo'>, ('/todos/<string:todo_id>',), {})]}
```
 
As you can see, My endpoint is [] and resources are full of staff.

What is the matter with that?

**Comment by lounagen** [comment]
Your 'app' field is None: did you initialize your api "Api(app)" with a (not None) flask app or blueprint, as shown in example files?

**Comment by wangshunping** [comment]
![image](https://cloud.githubusercontent.com/assets/10842398/12282264/cd44ffa2-b9d7-11e5-9c8d-7699289f95b2.png)

can I init using lazy way like flask-sqlalchemy ?

**Comment by lounagen** [comment]
I don't remember why (that was one year ago), but i faced the same pb at beginning and i resolved such a lazy init by using blueprints (check the sample/blueprints.py file) instead of classic app and api.init_app.

Bind your api to a blueprint in a global way:
```python
# Flask API handler for this particular API package version
current_blueprint = Blueprint(__name__, __name__)
# noinspection PyTypeChecker
api = Api(app=current_blueprint)
```
Decorate your api with the swagger docs method (you can do it at runtime on a submethod to allow to control what you expose or not according to a config file, instead of a globally way as shown in samples) and add resources endpoints to your api:
```python
def my_init(flask_app):
    api = swagger.docs(
        api,
        apiVersion="v1.2.3",
        basePath=url_prefix,
        api_spec_url="/api-docs",
        description="My Too Hype API"),
    )

    # Add a resource API to show on your web interface
    api.add_resource(my_pkg.MyServiceView,
                     '/my_pkg',
                     endpoint="{}.{}".format(__name__, "my_pkg.MyServiceView"))

    # Bind your blueprint to you flask_app arg
    flask_app.register_blueprint(current_blueprint, url_prefix=url_prefix)

```

Then bind you app to the blueprint in a lazy way at runtime, in a (main/wsgi)-like method:
````python
def main():
    app = Flask("xxx", static_folder='../static')
    my_init(app)
```

**Comment by wangshunping** [comment]
Actually , i didn't get it...


I have find some interesting info in chrome , could you please help with it ?


![image](https://cloud.githubusercontent.com/assets/10842398/12411205/8465f540-beb7-11e5-855b-cca9f6d09b47.png)

there is a js error ...


and i have got my info which can't show in the web page.

![image](https://cloud.githubusercontent.com/assets/10842398/12411218/a9c357ec-beb7-11e5-8c0d-f9ee5b902df8.png)

**Comment by wangshunping** [comment]
I have solved it . thanks !
