### ISSUE TITLE
Deploying on server

### ISSUE THREAD

**Issue by alseambusher** [rantav/flask-restful-swagger#95]
Hi,

I am trying to deploy a service written using flask-restful-swagger on nginx through a proxy. I am able to do this. However, urls of the static files have base "localhost:5000". For instance,

` <script src='http://localhost:5000/api/spec/_/static/swagger-ui.js' type='text/javascript'></script>`

How do I change it to,
` <script src='http://<some ip>/api/spec/_/static/swagger-ui.js' type='text/javascript'></script>`

**Comment by alseambusher** [comment]
I tried editing swagger.py   
`conf = {
    'base_url': url + api_spec_static,
    'full_base_url': url + api_spec_static
  }`

to

`conf = {
    'base_url': url + api_spec_static,
    'full_base_url': url + api_spec_static
  }`

Some things have started working. But it is still a broken experience

**Comment by sobolevn** [comment]
well, you are right. it's broken for now. new version is on it's way. it will be more customizable. but will break backwards compatibility. stay tuned.

**Comment by alseambusher** [comment]
I had to make a lot of changes in swagger.py and static/lib/swagger.js to get this working.
